version: '3.8'

services:
  server:
    image: ${DOCKER_HUB_USERNAME}/ai-growth-server:${IMAGE_TAG}
    container_name: aigrowthexa_server_blue
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    networks:
      - app_network

  client:
    image: ${DOCKER_HUB_USERNAME}/ai-growth-client:${IMAGE_TAG}
    container_name: aigrowthexa_client_blue
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - server
    networks:
      - app_network

networks:
  app_network:
    name: aigrowthexa_prod_network
    external: true
