version: '3.8'

services:
  mongodb:
    image: mongo:6.0-jammy
    container_name: aigrowthexa_prod_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=aigrowthexa
    volumes:
      - /var/lib/aigrowthexa/mongodb:/data/db
    networks:
      - app_network

networks:
  app_network:
    name: aigrowthexa_prod_network
    external: true
